//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("peluqueria_arte_colorModel", "FK__cliente__id_empr__1FCDBCEB", "empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(peluqueria_arte_colorModel.empresa), "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(peluqueria_arte_colorModel.cliente), true)]
[assembly: EdmRelationshipAttribute("peluqueria_arte_colorModel", "FK__cliente__id_soci__1ED998B2", "socios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(peluqueria_arte_colorModel.socios), "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(peluqueria_arte_colorModel.cliente), true)]
[assembly: EdmRelationshipAttribute("peluqueria_arte_colorModel", "FK__socios__id_empre__182C9B23", "empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(peluqueria_arte_colorModel.empresa), "socios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(peluqueria_arte_colorModel.socios), true)]
[assembly: EdmRelationshipAttribute("peluqueria_arte_colorModel", "FK__precio__id_produ__22AA2996", "producto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(peluqueria_arte_colorModel.producto), "precio", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(peluqueria_arte_colorModel.precio), true)]

#endregion

namespace peluqueria_arte_colorModel
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class peluqueria_arte_colorEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto peluqueria_arte_colorEntities usando la cadena de conexión encontrada en la sección 'peluqueria_arte_colorEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public peluqueria_arte_colorEntities() : base("name=peluqueria_arte_colorEntities", "peluqueria_arte_colorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto peluqueria_arte_colorEntities.
        /// </summary>
        public peluqueria_arte_colorEntities(string connectionString) : base(connectionString, "peluqueria_arte_colorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto peluqueria_arte_colorEntities.
        /// </summary>
        public peluqueria_arte_colorEntities(EntityConnection connection) : base(connection, "peluqueria_arte_colorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<empresa> empresa
        {
            get
            {
                if ((_empresa == null))
                {
                    _empresa = base.CreateObjectSet<empresa>("empresa");
                }
                return _empresa;
            }
        }
        private ObjectSet<empresa> _empresa;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<marca> marca
        {
            get
            {
                if ((_marca == null))
                {
                    _marca = base.CreateObjectSet<marca>("marca");
                }
                return _marca;
            }
        }
        private ObjectSet<marca> _marca;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<precio> precio
        {
            get
            {
                if ((_precio == null))
                {
                    _precio = base.CreateObjectSet<precio>("precio");
                }
                return _precio;
            }
        }
        private ObjectSet<precio> _precio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<producto> producto
        {
            get
            {
                if ((_producto == null))
                {
                    _producto = base.CreateObjectSet<producto>("producto");
                }
                return _producto;
            }
        }
        private ObjectSet<producto> _producto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<socios> socios
        {
            get
            {
                if ((_socios == null))
                {
                    _socios = base.CreateObjectSet<socios>("socios");
                }
                return _socios;
            }
        }
        private ObjectSet<socios> _socios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet empresa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToempresa(empresa empresa)
        {
            base.AddObject("empresa", empresa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet marca. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTomarca(marca marca)
        {
            base.AddObject("marca", marca);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet precio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToprecio(precio precio)
        {
            base.AddObject("precio", precio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproducto(producto producto)
        {
            base.AddObject("producto", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet socios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosocios(socios socios)
        {
            base.AddObject("socios", socios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cliente.
        /// </summary>
        /// <param name="id_cliente">Valor inicial de la propiedad id_cliente.</param>
        /// <param name="nombre_cliente">Valor inicial de la propiedad nombre_cliente.</param>
        /// <param name="apellido_cliente">Valor inicial de la propiedad apellido_cliente.</param>
        /// <param name="telefono_cliente">Valor inicial de la propiedad telefono_cliente.</param>
        /// <param name="direccion_cliente">Valor inicial de la propiedad direccion_cliente.</param>
        public static cliente Createcliente(global::System.Decimal id_cliente, global::System.String nombre_cliente, global::System.String apellido_cliente, global::System.String telefono_cliente, global::System.String direccion_cliente)
        {
            cliente cliente = new cliente();
            cliente.id_cliente = id_cliente;
            cliente.nombre_cliente = nombre_cliente;
            cliente.apellido_cliente = apellido_cliente;
            cliente.telefono_cliente = telefono_cliente;
            cliente.direccion_cliente = direccion_cliente;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                if (_id_cliente != value)
                {
                    Onid_clienteChanging(value);
                    ReportPropertyChanging("id_cliente");
                    _id_cliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cliente");
                    Onid_clienteChanged();
                }
            }
        }
        private global::System.Decimal _id_cliente;
        partial void Onid_clienteChanging(global::System.Decimal value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_cliente
        {
            get
            {
                return _nombre_cliente;
            }
            set
            {
                Onnombre_clienteChanging(value);
                ReportPropertyChanging("nombre_cliente");
                _nombre_cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_cliente");
                Onnombre_clienteChanged();
            }
        }
        private global::System.String _nombre_cliente;
        partial void Onnombre_clienteChanging(global::System.String value);
        partial void Onnombre_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido_cliente
        {
            get
            {
                return _apellido_cliente;
            }
            set
            {
                Onapellido_clienteChanging(value);
                ReportPropertyChanging("apellido_cliente");
                _apellido_cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido_cliente");
                Onapellido_clienteChanged();
            }
        }
        private global::System.String _apellido_cliente;
        partial void Onapellido_clienteChanging(global::System.String value);
        partial void Onapellido_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefono_cliente
        {
            get
            {
                return _telefono_cliente;
            }
            set
            {
                Ontelefono_clienteChanging(value);
                ReportPropertyChanging("telefono_cliente");
                _telefono_cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("telefono_cliente");
                Ontelefono_clienteChanged();
            }
        }
        private global::System.String _telefono_cliente;
        partial void Ontelefono_clienteChanging(global::System.String value);
        partial void Ontelefono_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion_cliente
        {
            get
            {
                return _direccion_cliente;
            }
            set
            {
                Ondireccion_clienteChanging(value);
                ReportPropertyChanging("direccion_cliente");
                _direccion_cliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion_cliente");
                Ondireccion_clienteChanged();
            }
        }
        private global::System.String _direccion_cliente;
        partial void Ondireccion_clienteChanging(global::System.String value);
        partial void Ondireccion_clienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> id_socios
        {
            get
            {
                return _id_socios;
            }
            set
            {
                Onid_sociosChanging(value);
                ReportPropertyChanging("id_socios");
                _id_socios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_socios");
                Onid_sociosChanged();
            }
        }
        private Nullable<global::System.Decimal> _id_socios;
        partial void Onid_sociosChanging(Nullable<global::System.Decimal> value);
        partial void Onid_sociosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                Onid_empresaChanging(value);
                ReportPropertyChanging("id_empresa");
                _id_empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa");
                Onid_empresaChanged();
            }
        }
        private Nullable<global::System.Decimal> _id_empresa;
        partial void Onid_empresaChanging(Nullable<global::System.Decimal> value);
        partial void Onid_empresaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__cliente__id_empr__1FCDBCEB", "empresa")]
        public empresa empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "empresa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresa> empresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresa>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "empresa", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__cliente__id_soci__1ED998B2", "socios")]
        public socios socios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<socios>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "socios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<socios>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "socios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<socios> sociosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<socios>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "socios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<socios>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "socios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class empresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto empresa.
        /// </summary>
        /// <param name="id_empresa">Valor inicial de la propiedad id_empresa.</param>
        /// <param name="nombre_empresa">Valor inicial de la propiedad nombre_empresa.</param>
        /// <param name="telefono_empresa">Valor inicial de la propiedad telefono_empresa.</param>
        /// <param name="direccion_empresa">Valor inicial de la propiedad direccion_empresa.</param>
        public static empresa Createempresa(global::System.Decimal id_empresa, global::System.String nombre_empresa, global::System.Decimal telefono_empresa, global::System.String direccion_empresa)
        {
            empresa empresa = new empresa();
            empresa.id_empresa = id_empresa;
            empresa.nombre_empresa = nombre_empresa;
            empresa.telefono_empresa = telefono_empresa;
            empresa.direccion_empresa = direccion_empresa;
            return empresa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                if (_id_empresa != value)
                {
                    Onid_empresaChanging(value);
                    ReportPropertyChanging("id_empresa");
                    _id_empresa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_empresa");
                    Onid_empresaChanged();
                }
            }
        }
        private global::System.Decimal _id_empresa;
        partial void Onid_empresaChanging(global::System.Decimal value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_empresa
        {
            get
            {
                return _nombre_empresa;
            }
            set
            {
                Onnombre_empresaChanging(value);
                ReportPropertyChanging("nombre_empresa");
                _nombre_empresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_empresa");
                Onnombre_empresaChanged();
            }
        }
        private global::System.String _nombre_empresa;
        partial void Onnombre_empresaChanging(global::System.String value);
        partial void Onnombre_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal telefono_empresa
        {
            get
            {
                return _telefono_empresa;
            }
            set
            {
                Ontelefono_empresaChanging(value);
                ReportPropertyChanging("telefono_empresa");
                _telefono_empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono_empresa");
                Ontelefono_empresaChanged();
            }
        }
        private global::System.Decimal _telefono_empresa;
        partial void Ontelefono_empresaChanging(global::System.Decimal value);
        partial void Ontelefono_empresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion_empresa
        {
            get
            {
                return _direccion_empresa;
            }
            set
            {
                Ondireccion_empresaChanging(value);
                ReportPropertyChanging("direccion_empresa");
                _direccion_empresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion_empresa");
                Ondireccion_empresaChanged();
            }
        }
        private global::System.String _direccion_empresa;
        partial void Ondireccion_empresaChanging(global::System.String value);
        partial void Ondireccion_empresaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__cliente__id_empr__1FCDBCEB", "cliente")]
        public EntityCollection<cliente> cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cliente>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cliente>("peluqueria_arte_colorModel.FK__cliente__id_empr__1FCDBCEB", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__socios__id_empre__182C9B23", "socios")]
        public EntityCollection<socios> socios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<socios>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "socios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<socios>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "socios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="marca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class marca : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto marca.
        /// </summary>
        /// <param name="id_marca">Valor inicial de la propiedad id_marca.</param>
        /// <param name="nombre_marca">Valor inicial de la propiedad nombre_marca.</param>
        /// <param name="existencia_marca">Valor inicial de la propiedad existencia_marca.</param>
        public static marca Createmarca(global::System.Decimal id_marca, global::System.String nombre_marca, global::System.String existencia_marca)
        {
            marca marca = new marca();
            marca.id_marca = id_marca;
            marca.nombre_marca = nombre_marca;
            marca.existencia_marca = existencia_marca;
            return marca;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_marca
        {
            get
            {
                return _id_marca;
            }
            set
            {
                if (_id_marca != value)
                {
                    Onid_marcaChanging(value);
                    ReportPropertyChanging("id_marca");
                    _id_marca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_marca");
                    Onid_marcaChanged();
                }
            }
        }
        private global::System.Decimal _id_marca;
        partial void Onid_marcaChanging(global::System.Decimal value);
        partial void Onid_marcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_marca
        {
            get
            {
                return _nombre_marca;
            }
            set
            {
                Onnombre_marcaChanging(value);
                ReportPropertyChanging("nombre_marca");
                _nombre_marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_marca");
                Onnombre_marcaChanged();
            }
        }
        private global::System.String _nombre_marca;
        partial void Onnombre_marcaChanging(global::System.String value);
        partial void Onnombre_marcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String existencia_marca
        {
            get
            {
                return _existencia_marca;
            }
            set
            {
                Onexistencia_marcaChanging(value);
                ReportPropertyChanging("existencia_marca");
                _existencia_marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("existencia_marca");
                Onexistencia_marcaChanged();
            }
        }
        private global::System.String _existencia_marca;
        partial void Onexistencia_marcaChanging(global::System.String value);
        partial void Onexistencia_marcaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="precio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class precio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto precio.
        /// </summary>
        /// <param name="id_precio">Valor inicial de la propiedad id_precio.</param>
        /// <param name="nombre_SERVICIO">Valor inicial de la propiedad nombre_SERVICIO.</param>
        /// <param name="precio_SERVICIO">Valor inicial de la propiedad precio_SERVICIO.</param>
        public static precio Createprecio(global::System.Decimal id_precio, global::System.String nombre_SERVICIO, global::System.Decimal precio_SERVICIO)
        {
            precio precio = new precio();
            precio.id_precio = id_precio;
            precio.nombre_SERVICIO = nombre_SERVICIO;
            precio.precio_SERVICIO = precio_SERVICIO;
            return precio;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_precio
        {
            get
            {
                return _id_precio;
            }
            set
            {
                if (_id_precio != value)
                {
                    Onid_precioChanging(value);
                    ReportPropertyChanging("id_precio");
                    _id_precio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_precio");
                    Onid_precioChanged();
                }
            }
        }
        private global::System.Decimal _id_precio;
        partial void Onid_precioChanging(global::System.Decimal value);
        partial void Onid_precioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_SERVICIO
        {
            get
            {
                return _nombre_SERVICIO;
            }
            set
            {
                Onnombre_SERVICIOChanging(value);
                ReportPropertyChanging("nombre_SERVICIO");
                _nombre_SERVICIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_SERVICIO");
                Onnombre_SERVICIOChanged();
            }
        }
        private global::System.String _nombre_SERVICIO;
        partial void Onnombre_SERVICIOChanging(global::System.String value);
        partial void Onnombre_SERVICIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal precio_SERVICIO
        {
            get
            {
                return _precio_SERVICIO;
            }
            set
            {
                Onprecio_SERVICIOChanging(value);
                ReportPropertyChanging("precio_SERVICIO");
                _precio_SERVICIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio_SERVICIO");
                Onprecio_SERVICIOChanged();
            }
        }
        private global::System.Decimal _precio_SERVICIO;
        partial void Onprecio_SERVICIOChanging(global::System.Decimal value);
        partial void Onprecio_SERVICIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                Onid_productoChanging(value);
                ReportPropertyChanging("id_producto");
                _id_producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_producto");
                Onid_productoChanged();
            }
        }
        private Nullable<global::System.Decimal> _id_producto;
        partial void Onid_productoChanging(Nullable<global::System.Decimal> value);
        partial void Onid_productoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__precio__id_produ__22AA2996", "producto")]
        public producto producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producto>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producto>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "producto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<producto> productoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producto>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<producto>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "producto", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto producto.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="nombre_producto">Valor inicial de la propiedad nombre_producto.</param>
        /// <param name="existencia_producto">Valor inicial de la propiedad existencia_producto.</param>
        public static producto Createproducto(global::System.Decimal id_producto, global::System.String nombre_producto, global::System.String existencia_producto)
        {
            producto producto = new producto();
            producto.id_producto = id_producto;
            producto.nombre_producto = nombre_producto;
            producto.existencia_producto = existencia_producto;
            return producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.Decimal _id_producto;
        partial void Onid_productoChanging(global::System.Decimal value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_producto
        {
            get
            {
                return _nombre_producto;
            }
            set
            {
                Onnombre_productoChanging(value);
                ReportPropertyChanging("nombre_producto");
                _nombre_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_producto");
                Onnombre_productoChanged();
            }
        }
        private global::System.String _nombre_producto;
        partial void Onnombre_productoChanging(global::System.String value);
        partial void Onnombre_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion_producto
        {
            get
            {
                return _descripcion_producto;
            }
            set
            {
                Ondescripcion_productoChanging(value);
                ReportPropertyChanging("descripcion_producto");
                _descripcion_producto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion_producto");
                Ondescripcion_productoChanged();
            }
        }
        private global::System.String _descripcion_producto;
        partial void Ondescripcion_productoChanging(global::System.String value);
        partial void Ondescripcion_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String existencia_producto
        {
            get
            {
                return _existencia_producto;
            }
            set
            {
                Onexistencia_productoChanging(value);
                ReportPropertyChanging("existencia_producto");
                _existencia_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("existencia_producto");
                Onexistencia_productoChanged();
            }
        }
        private global::System.String _existencia_producto;
        partial void Onexistencia_productoChanging(global::System.String value);
        partial void Onexistencia_productoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__precio__id_produ__22AA2996", "precio")]
        public EntityCollection<precio> precio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<precio>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "precio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<precio>("peluqueria_arte_colorModel.FK__precio__id_produ__22AA2996", "precio", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="socios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class socios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto socios.
        /// </summary>
        /// <param name="id_socios">Valor inicial de la propiedad id_socios.</param>
        /// <param name="nombres_socios">Valor inicial de la propiedad nombres_socios.</param>
        /// <param name="telefono_socios">Valor inicial de la propiedad telefono_socios.</param>
        /// <param name="direccion_socios">Valor inicial de la propiedad direccion_socios.</param>
        public static socios Createsocios(global::System.Decimal id_socios, global::System.String nombres_socios, global::System.Decimal telefono_socios, global::System.String direccion_socios)
        {
            socios socios = new socios();
            socios.id_socios = id_socios;
            socios.nombres_socios = nombres_socios;
            socios.telefono_socios = telefono_socios;
            socios.direccion_socios = direccion_socios;
            return socios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id_socios
        {
            get
            {
                return _id_socios;
            }
            set
            {
                if (_id_socios != value)
                {
                    Onid_sociosChanging(value);
                    ReportPropertyChanging("id_socios");
                    _id_socios = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_socios");
                    Onid_sociosChanged();
                }
            }
        }
        private global::System.Decimal _id_socios;
        partial void Onid_sociosChanging(global::System.Decimal value);
        partial void Onid_sociosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombres_socios
        {
            get
            {
                return _nombres_socios;
            }
            set
            {
                Onnombres_sociosChanging(value);
                ReportPropertyChanging("nombres_socios");
                _nombres_socios = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombres_socios");
                Onnombres_sociosChanged();
            }
        }
        private global::System.String _nombres_socios;
        partial void Onnombres_sociosChanging(global::System.String value);
        partial void Onnombres_sociosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal telefono_socios
        {
            get
            {
                return _telefono_socios;
            }
            set
            {
                Ontelefono_sociosChanging(value);
                ReportPropertyChanging("telefono_socios");
                _telefono_socios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono_socios");
                Ontelefono_sociosChanged();
            }
        }
        private global::System.Decimal _telefono_socios;
        partial void Ontelefono_sociosChanging(global::System.Decimal value);
        partial void Ontelefono_sociosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion_socios
        {
            get
            {
                return _direccion_socios;
            }
            set
            {
                Ondireccion_sociosChanging(value);
                ReportPropertyChanging("direccion_socios");
                _direccion_socios = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion_socios");
                Ondireccion_sociosChanged();
            }
        }
        private global::System.String _direccion_socios;
        partial void Ondireccion_sociosChanging(global::System.String value);
        partial void Ondireccion_sociosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                Onid_empresaChanging(value);
                ReportPropertyChanging("id_empresa");
                _id_empresa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_empresa");
                Onid_empresaChanged();
            }
        }
        private Nullable<global::System.Decimal> _id_empresa;
        partial void Onid_empresaChanging(Nullable<global::System.Decimal> value);
        partial void Onid_empresaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__cliente__id_soci__1ED998B2", "cliente")]
        public EntityCollection<cliente> cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cliente>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cliente>("peluqueria_arte_colorModel.FK__cliente__id_soci__1ED998B2", "cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("peluqueria_arte_colorModel", "FK__socios__id_empre__182C9B23", "empresa")]
        public empresa empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "empresa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<empresa> empresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<empresa>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<empresa>("peluqueria_arte_colorModel.FK__socios__id_empre__182C9B23", "empresa", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="peluqueria_arte_colorModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
